### ISSUE TITLE
How can I use it without Carthage

### ISSUE THREAD

**Issue by ghost** [mollywoodnini/ImageViewer#2]

**Comment by mollywoodnini** [comment]
There is no usage without carthage planned. If you need any help, hit me up!

**Comment by KNNMMDV** [comment]
I cannot build this in Xcode. Can you please upload one with Carthage included so it would be easy to build?

**Comment by mollywoodnini** [comment]
I edited the readme and added a much more detailled installation instruction. I hope it helps.

**Comment by KNNMMDV** [comment]
Can't you just upload buildable one please? Why would anybody want to use Carthage if it is not necessary :)

**Comment by mollywoodnini** [comment]
No, I won't. Carthage is de facto THE dependency manager for Cocoa / Swift. You can manually import Haneke and copy my swift files to your project. This should work flawlessly.

**Comment by KNNMMDV** [comment]
After importing Haneke it says "Reason: image not found" in the console.

**Comment by KNNMMDV** [comment]
I understand you love Carthage. But please send me buildable one.
